# This data file was generated by SC-IM.
# You almost certainly shouldn't edit it.

leftstring A0 = "Nuuk!"
leftstring A2 = "Colors"
leftstring B2 = "Shapes"
leftstring A3 = "Red"
leftstring B3 = "Man"
leftstring A4 = "Green"
leftstring B4 = "Animal"
leftstring A5 = "Blue"
leftstring B5 = "Tree"
leftstring A6 = "Yellow"
leftstring B6 = "Fire"
leftstring A7 = "Black"
leftstring B7 = "Mountain"
leftstring A8 = "White"
goto A5
